pub mod api;
mod paths;
mod pin_entry;

#[cfg(not(target_os = "android"))]
mod desktop;

/// Bridge generated by flutter_rust_bridge. Do not edit by hand.
///
/// The crate's strict lints deliberately do not apply to it: this is machine
/// code, it is rewritten in full on every `flutter_rust_bridge_codegen
/// generate`, and any edit to it would be lost silently. Our code lives in `api/`,
/// and the bans on unwrap/expect/panic apply there in full.
#[allow(
    unsafe_code,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]
mod frb_generated;
