// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/chat.dart';
import 'api/identity.dart';
import 'api/pin.dart';
import 'api/probe.dart';
import 'api/vault.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1737476983;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_apeiron',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<PlatformInt64> crateApiChatChatAcceptInvitation({
    required String textOfInvitation,
    required String name,
    required String firstText,
  });

  Future<void> crateApiChatChatCancelInvitation({required PlatformInt64 id});

  Future<List<ContactItem>> crateApiChatChatContacts();

  Future<InvitationItem> crateApiChatChatCreateInvitation({
    required String name,
  });

  Future<List<MessageItem>> crateApiChatChatHistory({
    required PlatformInt64 contact,
    PlatformInt64? before,
    required int limit,
  });

  Future<List<InvitationItem>> crateApiChatChatInvitations();

  Future<bool> crateApiChatChatPoll();

  Future<bool> crateApiChatChatRound({required PlatformInt64 contact});

  Future<String> crateApiChatChatSafetyNumber({required PlatformInt64 contact});

  Future<PlatformInt64> crateApiChatChatSend({
    required PlatformInt64 contact,
    required String message,
  });

  Future<void> crateApiChatChatSetVerified({
    required PlatformInt64 contact,
    required bool verified,
  });

  Future<PublicIdentityView?> crateApiIdentityCurrentIdentity();

  Future<String> crateApiProbeDhtProbeClearLog();

  Future<String> crateApiProbeDhtProbeGetOwn();

  Future<String> crateApiProbeDhtProbeGetPublic({
    required List<String> days,
    required int count,
  });

  Future<String> crateApiProbeDhtProbeLog();

  Future<String> crateApiProbeDhtProbePut({required int count});

  Future<PublicIdentityView> crateApiIdentityGenerateIdentity();

  Future<void> crateApiIdentityLockIdentity();

  Future<void> crateApiVaultLockVault();

  Future<VaultStatus> crateApiVaultPinChangeConfirm();

  Future<int> crateApiVaultPinChangeCurrent();

  Future<Uint8List> crateApiPinPinPadBegin();

  Future<void> crateApiPinPinPadClear();

  Future<int> crateApiPinPinPadErase();

  Future<PinPadPrefs> crateApiPinPinPadPrefs();

  Future<int> crateApiPinPinPadPress({required int position});

  Future<VaultStatus> crateApiVaultPinSetupConfirm();

  Future<int> crateApiVaultPinSetupFirst();

  Future<String> crateApiVaultPlatformDiagnostics();

  Future<String> crateApiIdentityPublicIdentityHex();

  Future<VaultStatus> crateApiVaultResetLegacy();

  Future<String> crateApiIdentitySafetyNumberWith({
    required String peerPublicHex,
  });

  Future<List<CheckLine>> crateApiVaultSelfCheck();

  Future<void> crateApiPinSetPinPadPrefs({
    required int digits,
    required bool scrambled,
  });

  Future<VaultStatus> crateApiVaultUnlockWithPin();

  Future<VaultStatus> crateApiVaultVaultStatus();

  Future<void> crateApiVaultWipeEverything();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<PlatformInt64> crateApiChatChatAcceptInvitation({
    required String textOfInvitation,
    required String name,
    required String firstText,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(textOfInvitation, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(firstText, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatChatAcceptInvitationConstMeta,
        argValues: [textOfInvitation, name, firstText],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatAcceptInvitationConstMeta =>
      const TaskConstMeta(
        debugName: "chat_accept_invitation",
        argNames: ["textOfInvitation", "name", "firstText"],
      );

  @override
  Future<void> crateApiChatChatCancelInvitation({required PlatformInt64 id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatChatCancelInvitationConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatCancelInvitationConstMeta =>
      const TaskConstMeta(
        debugName: "chat_cancel_invitation",
        argNames: ["id"],
      );

  @override
  Future<List<ContactItem>> crateApiChatChatContacts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_contact_item,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatChatContactsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatContactsConstMeta =>
      const TaskConstMeta(debugName: "chat_contacts", argNames: []);

  @override
  Future<InvitationItem> crateApiChatChatCreateInvitation({
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_invitation_item,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatChatCreateInvitationConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatCreateInvitationConstMeta =>
      const TaskConstMeta(
        debugName: "chat_create_invitation",
        argNames: ["name"],
      );

  @override
  Future<List<MessageItem>> crateApiChatChatHistory({
    required PlatformInt64 contact,
    PlatformInt64? before,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(contact, serializer);
          sse_encode_opt_box_autoadd_i_64(before, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message_item,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatChatHistoryConstMeta,
        argValues: [contact, before, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatHistoryConstMeta => const TaskConstMeta(
    debugName: "chat_history",
    argNames: ["contact", "before", "limit"],
  );

  @override
  Future<List<InvitationItem>> crateApiChatChatInvitations() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_invitation_item,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatChatInvitationsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatInvitationsConstMeta =>
      const TaskConstMeta(debugName: "chat_invitations", argNames: []);

  @override
  Future<bool> crateApiChatChatPoll() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatChatPollConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatPollConstMeta =>
      const TaskConstMeta(debugName: "chat_poll", argNames: []);

  @override
  Future<bool> crateApiChatChatRound({required PlatformInt64 contact}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(contact, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatChatRoundConstMeta,
        argValues: [contact],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatRoundConstMeta =>
      const TaskConstMeta(debugName: "chat_round", argNames: ["contact"]);

  @override
  Future<String> crateApiChatChatSafetyNumber({
    required PlatformInt64 contact,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(contact, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatChatSafetyNumberConstMeta,
        argValues: [contact],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatSafetyNumberConstMeta =>
      const TaskConstMeta(
        debugName: "chat_safety_number",
        argNames: ["contact"],
      );

  @override
  Future<PlatformInt64> crateApiChatChatSend({
    required PlatformInt64 contact,
    required String message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(contact, serializer);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatChatSendConstMeta,
        argValues: [contact, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatSendConstMeta => const TaskConstMeta(
    debugName: "chat_send",
    argNames: ["contact", "message"],
  );

  @override
  Future<void> crateApiChatChatSetVerified({
    required PlatformInt64 contact,
    required bool verified,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(contact, serializer);
          sse_encode_bool(verified, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiChatChatSetVerifiedConstMeta,
        argValues: [contact, verified],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatSetVerifiedConstMeta =>
      const TaskConstMeta(
        debugName: "chat_set_verified",
        argNames: ["contact", "verified"],
      );

  @override
  Future<PublicIdentityView?> crateApiIdentityCurrentIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_public_identity_view,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityCurrentIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityCurrentIdentityConstMeta =>
      const TaskConstMeta(debugName: "current_identity", argNames: []);

  @override
  Future<String> crateApiProbeDhtProbeClearLog() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProbeDhtProbeClearLogConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProbeDhtProbeClearLogConstMeta =>
      const TaskConstMeta(debugName: "dht_probe_clear_log", argNames: []);

  @override
  Future<String> crateApiProbeDhtProbeGetOwn() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProbeDhtProbeGetOwnConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProbeDhtProbeGetOwnConstMeta =>
      const TaskConstMeta(debugName: "dht_probe_get_own", argNames: []);

  @override
  Future<String> crateApiProbeDhtProbeGetPublic({
    required List<String> days,
    required int count,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(days, serializer);
          sse_encode_u_32(count, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProbeDhtProbeGetPublicConstMeta,
        argValues: [days, count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProbeDhtProbeGetPublicConstMeta =>
      const TaskConstMeta(
        debugName: "dht_probe_get_public",
        argNames: ["days", "count"],
      );

  @override
  Future<String> crateApiProbeDhtProbeLog() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProbeDhtProbeLogConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProbeDhtProbeLogConstMeta =>
      const TaskConstMeta(debugName: "dht_probe_log", argNames: []);

  @override
  Future<String> crateApiProbeDhtProbePut({required int count}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(count, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProbeDhtProbePutConstMeta,
        argValues: [count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProbeDhtProbePutConstMeta =>
      const TaskConstMeta(debugName: "dht_probe_put", argNames: ["count"]);

  @override
  Future<PublicIdentityView> crateApiIdentityGenerateIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_public_identity_view,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityGenerateIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityGenerateIdentityConstMeta =>
      const TaskConstMeta(debugName: "generate_identity", argNames: []);

  @override
  Future<void> crateApiIdentityLockIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityLockIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityLockIdentityConstMeta =>
      const TaskConstMeta(debugName: "lock_identity", argNames: []);

  @override
  Future<void> crateApiVaultLockVault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultLockVaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultLockVaultConstMeta =>
      const TaskConstMeta(debugName: "lock_vault", argNames: []);

  @override
  Future<VaultStatus> crateApiVaultPinChangeConfirm() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultPinChangeConfirmConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultPinChangeConfirmConstMeta =>
      const TaskConstMeta(debugName: "pin_change_confirm", argNames: []);

  @override
  Future<int> crateApiVaultPinChangeCurrent() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultPinChangeCurrentConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultPinChangeCurrentConstMeta =>
      const TaskConstMeta(debugName: "pin_change_current", argNames: []);

  @override
  Future<Uint8List> crateApiPinPinPadBegin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPinPinPadBeginConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPinPinPadBeginConstMeta =>
      const TaskConstMeta(debugName: "pin_pad_begin", argNames: []);

  @override
  Future<void> crateApiPinPinPadClear() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPinPinPadClearConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPinPinPadClearConstMeta =>
      const TaskConstMeta(debugName: "pin_pad_clear", argNames: []);

  @override
  Future<int> crateApiPinPinPadErase() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPinPinPadEraseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPinPinPadEraseConstMeta =>
      const TaskConstMeta(debugName: "pin_pad_erase", argNames: []);

  @override
  Future<PinPadPrefs> crateApiPinPinPadPrefs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pin_pad_prefs,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPinPinPadPrefsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPinPinPadPrefsConstMeta =>
      const TaskConstMeta(debugName: "pin_pad_prefs", argNames: []);

  @override
  Future<int> crateApiPinPinPadPress({required int position}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(position, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPinPinPadPressConstMeta,
        argValues: [position],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPinPinPadPressConstMeta =>
      const TaskConstMeta(debugName: "pin_pad_press", argNames: ["position"]);

  @override
  Future<VaultStatus> crateApiVaultPinSetupConfirm() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultPinSetupConfirmConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultPinSetupConfirmConstMeta =>
      const TaskConstMeta(debugName: "pin_setup_confirm", argNames: []);

  @override
  Future<int> crateApiVaultPinSetupFirst() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultPinSetupFirstConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultPinSetupFirstConstMeta =>
      const TaskConstMeta(debugName: "pin_setup_first", argNames: []);

  @override
  Future<String> crateApiVaultPlatformDiagnostics() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultPlatformDiagnosticsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultPlatformDiagnosticsConstMeta =>
      const TaskConstMeta(debugName: "platform_diagnostics", argNames: []);

  @override
  Future<String> crateApiIdentityPublicIdentityHex() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentityPublicIdentityHexConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityPublicIdentityHexConstMeta =>
      const TaskConstMeta(debugName: "public_identity_hex", argNames: []);

  @override
  Future<VaultStatus> crateApiVaultResetLegacy() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultResetLegacyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultResetLegacyConstMeta =>
      const TaskConstMeta(debugName: "reset_legacy", argNames: []);

  @override
  Future<String> crateApiIdentitySafetyNumberWith({
    required String peerPublicHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerPublicHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIdentitySafetyNumberWithConstMeta,
        argValues: [peerPublicHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentitySafetyNumberWithConstMeta =>
      const TaskConstMeta(
        debugName: "safety_number_with",
        argNames: ["peerPublicHex"],
      );

  @override
  Future<List<CheckLine>> crateApiVaultSelfCheck() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_check_line,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultSelfCheckConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultSelfCheckConstMeta =>
      const TaskConstMeta(debugName: "self_check", argNames: []);

  @override
  Future<void> crateApiPinSetPinPadPrefs({
    required int digits,
    required bool scrambled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(digits, serializer);
          sse_encode_bool(scrambled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPinSetPinPadPrefsConstMeta,
        argValues: [digits, scrambled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPinSetPinPadPrefsConstMeta => const TaskConstMeta(
    debugName: "set_pin_pad_prefs",
    argNames: ["digits", "scrambled"],
  );

  @override
  Future<VaultStatus> crateApiVaultUnlockWithPin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultUnlockWithPinConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultUnlockWithPinConstMeta =>
      const TaskConstMeta(debugName: "unlock_with_pin", argNames: []);

  @override
  Future<VaultStatus> crateApiVaultVaultStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVaultVaultStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultStatusConstMeta =>
      const TaskConstMeta(debugName: "vault_status", argNames: []);

  @override
  Future<void> crateApiVaultWipeEverything() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVaultWipeEverythingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultWipeEverythingConstMeta =>
      const TaskConstMeta(debugName: "wipe_everything", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  PublicIdentityView dco_decode_box_autoadd_public_identity_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_public_identity_view(raw);
  }

  @protected
  CheckLine dco_decode_check_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CheckLine(
      name: dco_decode_String(arr[0]),
      passed: dco_decode_bool(arr[1]),
      detail: dco_decode_String(arr[2]),
    );
  }

  @protected
  ContactItem dco_decode_contact_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ContactItem(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      state: dco_decode_contact_state(arr[2]),
      verified: dco_decode_bool(arr[3]),
    );
  }

  @protected
  ContactState dco_decode_contact_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ContactState.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  InvitationItem dco_decode_invitation_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return InvitationItem(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      expiresDay: dco_decode_u_32(arr[2]),
      text: dco_decode_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CheckLine> dco_decode_list_check_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_check_line).toList();
  }

  @protected
  List<ContactItem> dco_decode_list_contact_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_contact_item).toList();
  }

  @protected
  List<InvitationItem> dco_decode_list_invitation_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_invitation_item).toList();
  }

  @protected
  List<MessageItem> dco_decode_list_message_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message_item).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MessageItem dco_decode_message_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MessageItem(
      id: dco_decode_i_64(arr[0]),
      mine: dco_decode_bool(arr[1]),
      state: dco_decode_message_state(arr[2]),
      at: dco_decode_i_64(arr[3]),
      text: dco_decode_String(arr[4]),
    );
  }

  @protected
  MessageState dco_decode_message_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MessageState.values[raw as int];
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  PublicIdentityView? dco_decode_opt_box_autoadd_public_identity_view(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_public_identity_view(raw);
  }

  @protected
  PinPadPrefs dco_decode_pin_pad_prefs(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PinPadPrefs(
      digits: dco_decode_u_8(arr[0]),
      scrambled: dco_decode_bool(arr[1]),
    );
  }

  @protected
  PublicIdentityView dco_decode_public_identity_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PublicIdentityView(
      fingerprint: dco_decode_String(arr[0]),
      signingKeyHex: dco_decode_String(arr[1]),
      agreementKeyHex: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VaultState dco_decode_vault_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultState.values[raw as int];
  }

  @protected
  VaultStatus dco_decode_vault_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return VaultStatus(
      state: dco_decode_vault_state(arr[0]),
      message: dco_decode_String(arr[1]),
      levelName: dco_decode_String(arr[2]),
      levelRaw: dco_decode_i_32(arr[3]),
      hardwareBacked: dco_decode_bool(arr[4]),
      firstRun: dco_decode_bool(arr[5]),
      hasIdentity: dco_decode_bool(arr[6]),
      failures: dco_decode_u_32(arr[7]),
      waitSeconds: dco_decode_u_32(arr[8]),
      unlockMs: dco_decode_u_32(arr[9]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  PublicIdentityView sse_decode_box_autoadd_public_identity_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_public_identity_view(deserializer));
  }

  @protected
  CheckLine sse_decode_check_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_passed = sse_decode_bool(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return CheckLine(name: var_name, passed: var_passed, detail: var_detail);
  }

  @protected
  ContactItem sse_decode_contact_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_state = sse_decode_contact_state(deserializer);
    var var_verified = sse_decode_bool(deserializer);
    return ContactItem(
      id: var_id,
      name: var_name,
      state: var_state,
      verified: var_verified,
    );
  }

  @protected
  ContactState sse_decode_contact_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ContactState.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  InvitationItem sse_decode_invitation_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_expiresDay = sse_decode_u_32(deserializer);
    var var_text = sse_decode_String(deserializer);
    return InvitationItem(
      id: var_id,
      name: var_name,
      expiresDay: var_expiresDay,
      text: var_text,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CheckLine> sse_decode_list_check_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CheckLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_check_line(deserializer));
    }
    return ans_;
  }

  @protected
  List<ContactItem> sse_decode_list_contact_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ContactItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_contact_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<InvitationItem> sse_decode_list_invitation_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InvitationItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_invitation_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<MessageItem> sse_decode_list_message_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_item(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MessageItem sse_decode_message_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_mine = sse_decode_bool(deserializer);
    var var_state = sse_decode_message_state(deserializer);
    var var_at = sse_decode_i_64(deserializer);
    var var_text = sse_decode_String(deserializer);
    return MessageItem(
      id: var_id,
      mine: var_mine,
      state: var_state,
      at: var_at,
      text: var_text,
    );
  }

  @protected
  MessageState sse_decode_message_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MessageState.values[inner];
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PublicIdentityView? sse_decode_opt_box_autoadd_public_identity_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_public_identity_view(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PinPadPrefs sse_decode_pin_pad_prefs(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_digits = sse_decode_u_8(deserializer);
    var var_scrambled = sse_decode_bool(deserializer);
    return PinPadPrefs(digits: var_digits, scrambled: var_scrambled);
  }

  @protected
  PublicIdentityView sse_decode_public_identity_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fingerprint = sse_decode_String(deserializer);
    var var_signingKeyHex = sse_decode_String(deserializer);
    var var_agreementKeyHex = sse_decode_String(deserializer);
    return PublicIdentityView(
      fingerprint: var_fingerprint,
      signingKeyHex: var_signingKeyHex,
      agreementKeyHex: var_agreementKeyHex,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VaultState sse_decode_vault_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return VaultState.values[inner];
  }

  @protected
  VaultStatus sse_decode_vault_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_vault_state(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_levelName = sse_decode_String(deserializer);
    var var_levelRaw = sse_decode_i_32(deserializer);
    var var_hardwareBacked = sse_decode_bool(deserializer);
    var var_firstRun = sse_decode_bool(deserializer);
    var var_hasIdentity = sse_decode_bool(deserializer);
    var var_failures = sse_decode_u_32(deserializer);
    var var_waitSeconds = sse_decode_u_32(deserializer);
    var var_unlockMs = sse_decode_u_32(deserializer);
    return VaultStatus(
      state: var_state,
      message: var_message,
      levelName: var_levelName,
      levelRaw: var_levelRaw,
      hardwareBacked: var_hardwareBacked,
      firstRun: var_firstRun,
      hasIdentity: var_hasIdentity,
      failures: var_failures,
      waitSeconds: var_waitSeconds,
      unlockMs: var_unlockMs,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_public_identity_view(
    PublicIdentityView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_public_identity_view(self, serializer);
  }

  @protected
  void sse_encode_check_line(CheckLine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.passed, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_contact_item(ContactItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_contact_state(self.state, serializer);
    sse_encode_bool(self.verified, serializer);
  }

  @protected
  void sse_encode_contact_state(ContactState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_invitation_item(
    InvitationItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.expiresDay, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_check_line(
    List<CheckLine> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_check_line(item, serializer);
    }
  }

  @protected
  void sse_encode_list_contact_item(
    List<ContactItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_contact_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_invitation_item(
    List<InvitationItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_invitation_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message_item(
    List<MessageItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_message_item(MessageItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_bool(self.mine, serializer);
    sse_encode_message_state(self.state, serializer);
    sse_encode_i_64(self.at, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_message_state(MessageState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_public_identity_view(
    PublicIdentityView? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_public_identity_view(self, serializer);
    }
  }

  @protected
  void sse_encode_pin_pad_prefs(PinPadPrefs self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.digits, serializer);
    sse_encode_bool(self.scrambled, serializer);
  }

  @protected
  void sse_encode_public_identity_view(
    PublicIdentityView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fingerprint, serializer);
    sse_encode_String(self.signingKeyHex, serializer);
    sse_encode_String(self.agreementKeyHex, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vault_state(VaultState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_vault_status(VaultStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vault_state(self.state, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.levelName, serializer);
    sse_encode_i_32(self.levelRaw, serializer);
    sse_encode_bool(self.hardwareBacked, serializer);
    sse_encode_bool(self.firstRun, serializer);
    sse_encode_bool(self.hasIdentity, serializer);
    sse_encode_u_32(self.failures, serializer);
    sse_encode_u_32(self.waitSeconds, serializer);
    sse_encode_u_32(self.unlockMs, serializer);
  }
}
