// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `contact_item`, `invitation_item`, `message_item`, `text`

/// Every contact with its state.
Future<List<ContactItem>> chatContacts() =>
    RustLib.instance.api.crateApiChatChatContacts();

/// The invitations waiting for an answer.
Future<List<InvitationItem>> chatInvitations() =>
    RustLib.instance.api.crateApiChatChatInvitations();

/// A new invitation for `name` (the name the contact will get).
Future<InvitationItem> chatCreateInvitation({required String name}) =>
    RustLib.instance.api.crateApiChatChatCreateInvitation(name: name);

Future<void> chatCancelInvitation({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiChatChatCancelInvitation(id: id);

/// Accepts a pasted invitation. Returns the new contact.
Future<PlatformInt64> chatAcceptInvitation({
  required String textOfInvitation,
  required String name,
  required String firstText,
}) => RustLib.instance.api.crateApiChatChatAcceptInvitation(
  textOfInvitation: textOfInvitation,
  name: name,
  firstText: firstText,
);

/// A page of the history: at most `limit` entries older than `before`, newest first.
Future<List<MessageItem>> chatHistory({
  required PlatformInt64 contact,
  PlatformInt64? before,
  required int limit,
}) => RustLib.instance.api.crateApiChatChatHistory(
  contact: contact,
  before: before,
  limit: limit,
);

/// Writes a message; the next round puts it.
Future<PlatformInt64> chatSend({
  required PlatformInt64 contact,
  required String message,
}) => RustLib.instance.api.crateApiChatChatSend(
  contact: contact,
  message: message,
);

/// A round of one conversation through the DHT. Returns whether anything changed.
Future<bool> chatRound({required PlatformInt64 contact}) =>
    RustLib.instance.api.crateApiChatChatRound(contact: contact);

/// Asks every open invitation's inbox and runs a round of every conversation. Returns whether
/// anything changed.
Future<bool> chatPoll() => RustLib.instance.api.crateApiChatChatPoll();

/// The safety number with the contact: the same string on both sides.
Future<String> chatSafetyNumber({required PlatformInt64 contact}) =>
    RustLib.instance.api.crateApiChatChatSafetyNumber(contact: contact);

/// Marks the contact as verified — only ever the owner's own act — or takes the mark back.
Future<void> chatSetVerified({
  required PlatformInt64 contact,
  required bool verified,
}) => RustLib.instance.api.crateApiChatChatSetVerified(
  contact: contact,
  verified: verified,
);

class ContactItem {
  final PlatformInt64 id;
  final String name;
  final ContactState state;
  final bool verified;

  const ContactItem({
    required this.id,
    required this.name,
    required this.state,
    required this.verified,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ state.hashCode ^ verified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          state == other.state &&
          verified == other.verified;
}

enum ContactState {
  /// I accepted their invitation; they have not taken my reply yet.
  waiting,
  live,

  /// Their invitation expired unanswered.
  notAccepted,

  /// Someone else answered their invitation first.
  taken,

  /// The conversation does not load.
  damaged,
}

class InvitationItem {
  final PlatformInt64 id;
  final String name;

  /// The last UTC day, counted from 1970-01-01, on which it can be accepted.
  final int expiresDay;

  /// The text to send: `apeiron:…`.
  final String text;

  const InvitationItem({
    required this.id,
    required this.name,
    required this.expiresDay,
    required this.text,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ expiresDay.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InvitationItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          expiresDay == other.expiresDay &&
          text == other.text;
}

class MessageItem {
  final PlatformInt64 id;
  final bool mine;
  final MessageState state;

  /// Unix seconds: written (mine) or decrypted (theirs).
  final PlatformInt64 at;
  final String text;

  const MessageItem({
    required this.id,
    required this.mine,
    required this.state,
    required this.at,
    required this.text,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      mine.hashCode ^
      state.hashCode ^
      at.hashCode ^
      text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          mine == other.mine &&
          state == other.state &&
          at == other.at &&
          text == other.text;
}

enum MessageState {
  queued,
  sent,
  delivered,
  notDelivered,
  addressTaken,
  received,

  /// Some of the peer's messages will never be read.
  lost,
}
