// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Создаёт новую личность, заменяя текущую.
///
/// Прежняя уничтожается, её ключи затираются. На этапе 2 это станет необратимой
/// операцией с подтверждением: смена личности рвёт все существующие переписки.
Future<PublicIdentityView> generateIdentity() =>
    RustLib.instance.api.crateApiIdentityGenerateIdentity();

/// Текущая личность, если она разблокирована.
Future<PublicIdentityView?> currentIdentity() =>
    RustLib.instance.api.crateApiIdentityCurrentIdentity();

/// Блокировка: уничтожает `Identity` и затирает ключи.
///
/// Вызывается при уходе приложения в фон и при гашении экрана — решение R-001.
Future<void> lockIdentity() =>
    RustLib.instance.api.crateApiIdentityLockIdentity();

/// Число сверки с собеседником по его публичной личности.
///
/// Обе стороны получают одну и ту же строку. Расхождение означает, что между вами
/// кто-то есть, и переписку начинать нельзя.
Future<String> safetyNumberWith({required String peerPublicHex}) => RustLib
    .instance
    .api
    .crateApiIdentitySafetyNumberWith(peerPublicHex: peerPublicHex);

/// Публичная личность целиком, hex — то, что кодируется в QR при добавлении контакта.
Future<String> publicIdentityHex() =>
    RustLib.instance.api.crateApiIdentityPublicIdentityHex();

/// То, что разрешено показывать. Секретов не содержит.
class PublicIdentityView {
  /// Тридцать цифр шестью группами — то, что читают вслух при сверке.
  final String fingerprint;

  /// Публичный ключ подписи Ed25519, hex.
  final String signingKeyHex;

  /// Публичный ключ согласования X25519, hex.
  final String agreementKeyHex;

  const PublicIdentityView({
    required this.fingerprint,
    required this.signingKeyHex,
    required this.agreementKeyHex,
  });

  @override
  int get hashCode =>
      fingerprint.hashCode ^ signingKeyHex.hashCode ^ agreementKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PublicIdentityView &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          signingKeyHex == other.signingKeyHex &&
          agreementKeyHex == other.agreementKeyHex;
}
