// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `view`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Creates a new identity and saves it.
///
/// The device account and the sigchain (identity log) are created with it: apart
/// they are meaningless. The operation is irreversible — changing the identity
/// breaks all existing conversations — and the vault must be open by this point.
Future<PublicIdentityView> generateIdentity() =>
    RustLib.instance.api.crateApiIdentityGenerateIdentity();

/// The current identity, if the vault is open.
Future<PublicIdentityView?> currentIdentity() =>
    RustLib.instance.api.crateApiIdentityCurrentIdentity();

/// Locking: locks the vault and wipes the keys.
///
/// Called when the app goes to the background and when the screen turns off —
/// decision R-001.
Future<void> lockIdentity() =>
    RustLib.instance.api.crateApiIdentityLockIdentity();

/// Safety number with a peer, from their public identity.
///
/// Both sides get the same string. A mismatch means someone is between
/// you, and the conversation must not be started.
Future<String> safetyNumberWith({required String peerPublicHex}) => RustLib
    .instance
    .api
    .crateApiIdentitySafetyNumberWith(peerPublicHex: peerPublicHex);

/// The whole public identity, hex — what is encoded in the QR code when adding
/// a contact.
Future<String> publicIdentityHex() =>
    RustLib.instance.api.crateApiIdentityPublicIdentityHex();

/// What is allowed to be shown. Contains no secrets.
class PublicIdentityView {
  /// Thirty digits in six groups — what is read aloud during verification.
  final String fingerprint;

  /// Public Ed25519 signing key, hex.
  final String signingKeyHex;

  /// Public X25519 key-agreement key, hex.
  final String agreementKeyHex;

  const PublicIdentityView({
    required this.fingerprint,
    required this.signingKeyHex,
    required this.agreementKeyHex,
  });

  @override
  int get hashCode =>
      fingerprint.hashCode ^ signingKeyHex.hashCode ^ agreementKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PublicIdentityView &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          signingKeyHex == other.signingKeyHex &&
          agreementKeyHex == other.agreementKeyHex;
}
