// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Starts an attempt: a fresh random layout and an empty pad.
///
/// Returns the digit shown at each of the ten positions, in reading order: three rows of
/// three, then the middle of the bottom row.
Future<Uint8List> pinPadBegin() =>
    RustLib.instance.api.crateApiPinPinPadBegin();

/// The key at `position` was tapped. Returns how many digits are entered.
Future<int> pinPadPress({required int position}) =>
    RustLib.instance.api.crateApiPinPinPadPress(position: position);

/// Removes the last digit. Returns how many digits are entered.
Future<int> pinPadErase() => RustLib.instance.api.crateApiPinPinPadErase();

/// Forgets everything typed, including a pending first entry of a new PIN.
Future<void> pinPadClear() => RustLib.instance.api.crateApiPinPinPadClear();
