// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `unix_s`

/// Puts `count` probe items with random seeds and remembers them on this phone.
///
/// The report lists the seeds: the desktop fetches the same items from them hours later.
/// Items are put in parallel — one put waits for the whole query, several seconds.
Future<String> dhtProbePut({required int count}) =>
    RustLib.instance.api.crateApiProbeDhtProbePut(count: count);

/// Fetches the items this phone put earlier, and says how old they are.
Future<String> dhtProbeGetOwn() =>
    RustLib.instance.api.crateApiProbeDhtProbeGetOwn();

/// Fetches the desktop's items for `day` — public seeds, so nothing had to be sent here.
Future<String> dhtProbeGetPublic({required String day, required int count}) =>
    RustLib.instance.api.crateApiProbeDhtProbeGetPublic(day: day, count: count);
