// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `log_path`, `newest`, `own_report`, `public_report`, `put_report`, `record`, `unix_s`, `utc`, `verdict`

/// The log of every step so far, oldest first. Empty if nothing was measured yet.
Future<String> dhtProbeLog() => RustLib.instance.api.crateApiProbeDhtProbeLog();

/// Forgets the log. The seeds stay: "check own" still finds what was put.
Future<String> dhtProbeClearLog() =>
    RustLib.instance.api.crateApiProbeDhtProbeClearLog();

/// Puts `count` probe items with random seeds and remembers them on this phone.
///
/// The report lists the seeds: the desktop fetches the same items from them hours later.
/// Items are put in parallel — one put waits for the whole query, several seconds.
Future<String> dhtProbePut({required int count}) =>
    RustLib.instance.api.crateApiProbeDhtProbePut(count: count);

/// Fetches the items this phone put earlier, all at once, and lists each with its age.
Future<String> dhtProbeGetOwn() =>
    RustLib.instance.api.crateApiProbeDhtProbeGetOwn();

/// Fetches the desktop's items for each of `days` — public seeds, so nothing had to be sent
/// here. One node for all of them and every lookup at once: bootstrapping twice and looking
/// up one by one made this take minutes.
Future<String> dhtProbeGetPublic({
  required List<String> days,
  required int count,
}) => RustLib.instance.api.crateApiProbeDhtProbeGetPublic(
  days: days,
  count: count,
);
