// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bare`, `create_identity`, `from_error`, `from_session`, `open_session`, `state`, `waiting`, `with_identity`, `writer`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Session`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// The current state, without an attempt to open anything.
///
/// For a locked vault this also says whether a delay is running, so that the screen can
/// show a countdown instead of a pad that would only answer "wait".
Future<VaultStatus> vaultStatus() =>
    RustLib.instance.api.crateApiVaultVaultStatus();

/// Tries the PIN typed on the pad.
Future<VaultStatus> unlockWithPin() =>
    RustLib.instance.api.crateApiVaultUnlockWithPin();

/// Keeps the typed digits as the first entry of a new PIN. Returns their count.
Future<int> pinSetupFirst() =>
    RustLib.instance.api.crateApiVaultPinSetupFirst();

/// Compares the confirmation with the first entry and, if they match, creates the vault.
///
/// The comparison is here, in Rust, and not in Dart: Dart never holds either entry.
Future<VaultStatus> pinSetupConfirm() =>
    RustLib.instance.api.crateApiVaultPinSetupConfirm();

/// Clears data of a test build before the PIN, at the owner's request.
///
/// Refuses anything else: a PIN vault is erased only through [`wipe_everything`], and
/// only from the states where the key is already lost.
Future<VaultStatus> resetLegacy() =>
    RustLib.instance.api.crateApiVaultResetLegacy();

/// Locks: destroys the database key and everything derived from it, and forgets any
/// digits on the pad.
///
/// Called when the app goes to the background and when the screen turns off —
/// decision R-001.
Future<void> lockVault() => RustLib.instance.api.crateApiVaultLockVault();

/// Erases everything cryptographically (R-005): destroys the key, not the data.
///
/// Offered only when the key is already lost; the action is irreversible.
Future<void> wipeEverything() =>
    RustLib.instance.api.crateApiVaultWipeEverything();

/// Runs the self-check on this device.
Future<List<CheckLine>> selfCheck() =>
    RustLib.instance.api.crateApiVaultSelfCheck();

/// Platform diagnostics, one line per fact.
///
/// Needed because there is only one on-device check: an install must answer all
/// questions at once, not just the one someone thought to ask. The report is shown as is
/// and forwarded in full. Contains no secrets.
Future<String> platformDiagnostics() =>
    RustLib.instance.api.crateApiVaultPlatformDiagnostics();

/// One line of the self-check report.
class CheckLine {
  final String name;
  final bool passed;
  final String detail;

  const CheckLine({
    required this.name,
    required this.passed,
    required this.detail,
  });

  @override
  int get hashCode => name.hashCode ^ passed.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckLine &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          passed == other.passed &&
          detail == other.detail;
}

/// What state the vault is in.
enum VaultState {
  /// Open and ready.
  opened,

  /// Locked: the database key is wiped, the PIN is needed.
  locked,

  /// No vault yet: a PIN has to be set.
  pinSetupRequired,

  /// The two entries of a new PIN differ; setting starts over.
  pinMismatch,

  /// The PIN was wrong. See `failures` and `wait_seconds`.
  wrongPin,

  /// Too many failures: wait `wait_seconds`. Nothing was tried.
  delayed,

  /// Data of a test build before the PIN. Cannot be opened; the owner decides to reset.
  legacyData,

  /// The key is gone from the secure module. Nothing can decrypt.
  keyGone,

  /// The secure module holds a different key. Nothing can decrypt.
  keyMismatch,

  /// Transient failure. The data is intact, retry.
  retry,

  /// There is no hardware store on this platform.
  unavailable,
}

/// What to show about the vault.
class VaultStatus {
  final VaultState state;

  /// Explanation for a person. Empty string if there is nothing to explain.
  final String message;

  /// Level name: StrongBox, TEE, software, hardware without specifics.
  final String levelName;

  /// The raw number from `KeyInfo.getSecurityLevel()`. Shown alongside so that an
  /// unfamiliar value is visible, not replaced by the nearest familiar one.
  final int levelRaw;

  /// Whether the key is in hardware, as reported by the system.
  final bool hardwareBacked;

  /// Whether the vault was created just now.
  final bool firstRun;

  /// Whether the vault holds an identity.
  final bool hasIdentity;

  /// Wrong PINs in a row.
  final int failures;

  /// Seconds to wait before the next attempt.
  final int waitSeconds;

  /// How long the last unlock took (Argon2id plus the hardware chain), in milliseconds.
  final int unlockMs;

  const VaultStatus({
    required this.state,
    required this.message,
    required this.levelName,
    required this.levelRaw,
    required this.hardwareBacked,
    required this.firstRun,
    required this.hasIdentity,
    required this.failures,
    required this.waitSeconds,
    required this.unlockMs,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      message.hashCode ^
      levelName.hashCode ^
      levelRaw.hashCode ^
      hardwareBacked.hashCode ^
      firstRun.hashCode ^
      hasIdentity.hashCode ^
      failures.hashCode ^
      waitSeconds.hashCode ^
      unlockMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultStatus &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          message == other.message &&
          levelName == other.levelName &&
          levelRaw == other.levelRaw &&
          hardwareBacked == other.hardwareBacked &&
          firstRun == other.firstRun &&
          hasIdentity == other.hasIdentity &&
          failures == other.failures &&
          waitSeconds == other.waitSeconds &&
          unlockMs == other.unlockMs;
}
