// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Диагностика платформы одной строкой на каждый факт.
///
/// Нужна затем, что проверка на устройстве одна: установка обязана ответить на
/// все вопросы сразу, а не на тот, который догадались задать. Отчёт
/// показывается как есть и пересылается целиком.
Future<String> platformDiagnostics() =>
    RustLib.instance.api.crateApiVaultPlatformDiagnostics();
